[package]
name = "foo_rs"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[lib]
name = "foo_rs"
crate-type = ["staticlib", "lib"]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
libc = "0.2.112"
rand = "0.8.4"

[build-dependencies]
cc = "1.0.72"
cmake = "0.1"